### ISSUE TITLE
My module has dependencies. Action fails...

### ISSUE THREAD

**Issue by tig** [natescherer/publish-powershell-action#10]
<img width="360" alt="image" src="https://github.com/natescherer/publish-powershell-action/assets/585482/4914775c-b64d-41c7-b37b-3c14b97a1465">

`F7History.psd1` includes:

```
# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('Microsoft.PowerShell.ConsoleGuiTools', 'PSReadLine')
```

When I publish locally with

```ps1
publish-Module -Path .\F7History\ -NuGetApiKey <key>
```

It works fine. What am i doing wrong?

```yaml
name: Publish to PowerShell Gallery

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    # steps:
    #   - name: Check out code
    #     uses: actions/checkout@v2

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Publish PowerShell
        uses: natescherer/publish-powershell-action@v1.0.3
        with:
          token: ${{ secrets.F7HISTORY_GALLERY_KEY }}
          target: gallery
          path: src
```
